apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: HyperConverged
      name: kubevirt-hyperconverged
    patch: |-
      - op: replace
        path: /spec/storageImport/insecureRegistries/0
        value: 'witness-node.uotest01.poc.lab.local:8443'
