---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-storage
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: openshift-local-storage
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 2-operators/local-storage/overlays/stable
    repoURL: >-
      https://github.com/ahussey-redhat/deployables-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true