---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: test
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 3-workloads/test
    repoURL: >-
      https://github.com/ahussey-redhat/deployables-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
