---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: open-cluster-management
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 2-operators/acm/aggregate/hub/default/
    repoURL: >-
      https://github.com/ahussey-redhat/deployables-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
