apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - banner.yml
patches:
  - target:
      kind: ConsoleNotification
      name: global-notification-top
    patch: |-
      - op: replace
        path: /spec/text
        value: 'Configured by CORE'
  - target:
      kind: ConsoleNotification
      name: global-notification-bottom
    patch: |-
      - op: replace
        path: /spec/text
        value: 'Contact core-admin@poc.lab.local for L3 support'