apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: UpdateService
      name: update-service
    patch: |-
      - op: replace
        path: /spec/releases
        value: 'witness-node.uotest01.poc.lab.local:8443/openshift/release-images'
    patch: |-
      - op: replace
        path: /spec/graphDataImage
        value: 'witness-node.uotest01.poc.lab.local:8443/openshift/graph-image:latest'