---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  annotations:
  name: management-network
spec:
  desiredState:
    interfaces:
      - bridge:
          options:
            stp:
              enabled: false
          port:
            - name: bond0
        ipv4:
          enabled: true
          dhcp: true
          auto-dns: true
          auto-gateway: true
          auto-routes: true
        ipv6:
          enabled: false
        name: br100
        state: up
        type: linux-bridge
