apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-ansible-automation-platform
resources:
  - namespace.yml
  - operatorgroup.yml
  - subscription.yml
  - controller.yml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#  - hub.yml
#  - eda.yml