---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications/devspaces.yml
  - applications/misc.yml
  - applications/nmstate.yml
  - applications/pipelines.yml
  - applications/virtualization.yml