---
apiVersion: updateservice.operator.openshift.io/v1
kind: UpdateService
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: update-service
  namespace: openshift-update-service
spec:
  replicas: 2
  releases: quay.io/openshift-release-dev/ocp-release
  graphDataImage: witness-node.uotest01.poc.lab.local:8443/openshift/graph-image:latest
